### ISSUE TITLE
Support runtime-sized arrays

### ISSUE THREAD

**Issue by badicsalex** [ScanMountGoat/wgsl_to_wgpu#43]
Let's say I have the following WGSL code, which is then used by a compute shader:

```
struct Data {
    some_param_1: u32,
    some_param_2: u32,
    data: array<u32>,
}
@group(0) @binding(0)
var <storage, read_write> data: Data;
```

The way this works is that WGSL will calculate the actual array length from the binding size.

Unfortunately `wgsl_to_wgpu` generates a zero length array from this, which makes `encase` unhappy and is also kind of unusable Rust-side. Fortunately `encase` has functionality to handle this case; by marking the field with the `#[size(runtime)]` pseuodo-attribute. Then the field can be a `Vec` and that is correctly handled by the encase `read` and `write` functions.

Of course this breaks bytemuck or raw casting, but the current zero-length array thing doesn't work that well anyway.

Now the question is, is it a good idea to special-case this (`derive_encase == true` and the array is runtime-sized)? Or something else should be done? I'd be happy to make a PR, but not until we agree on a solution.

**Comment by ScanMountGoat** [comment]
We already support the case where a runtime-sized array is used directly like `var<storage, read> data: array<u32>`. The case where runtime-sized arrays are used in a struct isn't handled correctly. The length calculation requires the runtime-sized array in a struct to be the last field. I'm not sure if there's a way to encode this safely in Rust with bytemuck since the type would be dynamically sized. This sounds like it should probably just be an error when using bytemuck.

We could allow this when using encase and not bytemuck. Does encase give a compile error if the `#[size(runtime)]` attribute is missing?

https://www.w3.org/TR/WGSL/#buffer-binding-determines-runtime-sized-array-element-count

**Comment by badicsalex** [comment]
>Does encase give a compile error if the #[size(runtime)] attribute is missing?
Yes:
```
error[E0080]: evaluation of `encase::types::array::<impl encase::ShaderType for [shaders::ffd::FfdKeypoint; 0]>::METADATA` failed
  --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/encase-0.5.0/src/types/array.rs:31:18
   |
31 |             0 => panic!("0 sized arrays are not supported!"),
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at '0 sized arrays are not supported!', /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/encase-0.5.0/src/types/array.rs:31:18
```

The offending struct looks like this:
```rust
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, encase::ShaderType)]
pub struct FfdKeypoints {
    pub num: u32,
    pub points: [FfdKeypoint; 0],
}
```

What I would generate instead is this:

```rust
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, encase::ShaderType)]
pub struct FfdKeypoints {
    pub num: u32,
    #[size(runtime)]
    pub points: Vec<FfdKeypoint>,
}
```

And throw a compile error if `encase` is not used (or `bytemuck` is). Oh, and at that point `#[repr(C)]` can be dropped, since it shouldn't be casted anyway.

(IIRC Bytemuck can handle DST arrays (raw `[T]`), but that would make the struct itself `?Sized`, which is kind of a pain to use (e.g. no copy, no clone, no way to instantiate on stack, etc.).)

**Comment by ScanMountGoat** [comment]
> Now the question is, is it a good idea to special-case this (derive_encase == true and the array is runtime-sized)? Or something else should be done?

I think this is fine. The current code doesn't support runtime-sized arrays at all. I'm not sure why I chose to emit a zero length in that function. We can just modify the `array_length` and `rust_type` functions to return `Vec` with the appropriate attribute when deriving `encase`. I think we also need to drop the derive for `Copy` in this case because of `Vec`. It should be easy enough to add test cases in `structs.rs` for this.

> And throw a compile error if encase is not used (or bytemuck is). Oh, and at that point #[repr(C)] can be dropped, since it shouldn't be casted anyway.

Yeah. This should only work when deriving `encase` and not `bytemuck`. I don't think there's any advantage to having `repr(C)` without `bytemuck`.

**Comment by ScanMountGoat** [comment]
> I'd be happy to make a PR, but not until we agree on a solution.

That would be great if the points discussed above look ok to you.

**Comment by badicsalex** [comment]
Yeah, sounds good, I'll prepare a PR in the following days.
