### ISSUE TITLE
`set_bind_groups` is not a method of `BindGroups`

### ISSUE THREAD

**Issue by ItzShiney** [ScanMountGoat/wgsl_to_wgpu#49]
`set_bind_groups` could be turned into a method of `BindGroups`

For example:
```rs
pub fn set_bind_groups<'a>(
    pass: &mut wgpu::RenderPass<'a>,
    bind_groups: BindGroups<'a>,
) {
    bind_groups.bind_group0.set(pass);
    bind_groups.bind_group1.set(pass);
}
```
->
```rs
impl<'a> BindGroups<'a> {
    // Assuming BindGroups is Copy
    pub fn set(self, &mut wgpu::RenderPass<'a>) {
        self.bind_group0.set(pass);
        self.bind_group1.set(pass);
    }
}
```

**Comment by ScanMountGoat** [comment]
This could definitely be a method, but I wonder if it's necessary to even have a struct at all. The bind group code for this repository is the oldest and should probably be reworked at some point. The struct doesn't own any of its data, so it's unlikely to live for very long. The method syntax isn't really any simpler if you need to recreate the struct each time. How do you typically set bind groups in your applications?

```rust
// Current Syntax
crate::shader::my_shader::bind_groups::set_bind_groups(
    &mut render_pass,
    crate::shader::my_shader::bind_groups::BindGroups {
        bind_group0: &self.bind_group0,
        bind_group1: &self.bind_group1,
        bind_group2: &self.bind_group2,
        bind_group3: &self.bind_group3,
    },
);

// Method Syntax
crate::shader::my_shader::bind_groups::BindGroups {
    bind_group0: &self.bind_group0,
    bind_group1: &self.bind_group1,
    bind_group2: &self.bind_group2,
    bind_group3: &self.bind_group3,
}.set(&mut render_pass);

// Potential Syntax
crate::shader::my_shader::set_bind_groups(
    &mut render_pass,
    &self.bind_group0,
    &self.bind_group1,
    &self.bind_group2,
    &self.bind_group3,
);
```

**Comment by ItzShiney** [comment]
The struct is useful to automatically update function arguments, in case a new binding group was added
I do have such place in my current project (and will have more in future), so the struct comes in handy
```rs
impl SmthDrawer {
    fn draw(&self, render_pass: &mut RenderPass, /* smth drawing params */, bind_groups: BindGroups) {
        bind_groups.set(render_pass);

        // draw smth
    }
}
```

**Comment by ScanMountGoat** [comment]
The recommended way to use bind groups is to sort them by how frequently they get updated. This would be done by setting bind group 0 once per frame, bind group 1 once per material, etc. The performance advantage is pretty minor in practice if you have few draw calls. The main advantage in my opinion is that the rendering code can be cleaner since each draw call doesn't need to hold shared resources like camera and render settings. I'll try and update the readme to explain this better.

In practice, it's often convenient to just redundantly set all resources for each draw call. Using the bind groups as a function parameter like in your example makes sense. I can support method syntax on BindGroups and still simplify set_bind_groups to take the up to 4 bind group parameters directly.

**Comment by ScanMountGoat** [comment]
Do you need `BindGroups` to be `Copy` for your use case @ItzShiney? I've implemented the set method on the latest commit by taking `&self` instead of `self`. Your example code should still work with the new code.

**Comment by ItzShiney** [comment]
I don't think I do, but I don't see any point in not deriving it
