### ISSUE TITLE
Debug labels

### ISSUE THREAD

**Issue by 9SMTM6** [ScanMountGoat/wgsl_to_wgpu#59]
Hey there,

this is a quite helpful package. I'm currently looking at primarily your package and the fork wgsl_bindgen.

wgsl_bindgen does a bunch of stuff by default, that I'm not sure I need. However it does also do one thing, that I currently consider quite crucial. It generates debug labels for everything that accepts them. That I'm not really able to retrofit with the generated source from your package,  since you only provide functions that immediately pass descriptors to the device.

For me to consider this package I'd either need to access the descriptors without directly passing them to the device (ShaderModuleDescriptor can be const actually) or allow to either automatically infer some labels, or to pass one label for all generated code for one wgsl source (which would be sufficient granularity at least for me).

**Comment by ScanMountGoat** [comment]
What debug labels do you need to set that aren't exposed currently? I usually just label the pipelines themselves instead of their descriptors.

**Comment by 9SMTM6** [comment]
IIRC the concrete example was BindGroupLayouts or BindGroups.

But in all honesty. I have been using wgsl_bindgen inbetween, which did name these - not configurably, but uniquely - and also added imports and validation. But its usage of naga_oil now seems to prevent usage of pipeline-overridable constants (unless you ship and use naga_oil at runtime). Uncertain how I'll continue now.

**Comment by 9SMTM6** [comment]
Thank you for the quick response. 

Honestly I'm a total noob when it comes to graphics programming. All I did before the project I'm working on now, was at best writing OpenCL stuff.

I simply want as much debug information as possible, or at least the ability to set these values when I come upon an issue.

I have not figured out RenderDoc, or any other debugger yet.  IIRC the issue was that RenderDoc doesn't support Wayland (youd have to compile it yourself, if thats going to be the only issue, since renderdoc isnt tested with wayland), if combined with no support for webgpu beyond debugging in some intermediate language...

So yeah. My debugging experience with wgpu is limited to static analysis (wgpu_bindgen helped there, alternatively the good old eyeball and brain) and making sense of the runtime errors I get back. It worked alright so far, but I take what I get.

Feel free to close this, if I'm not part of your target demographic :sweat_smile: .

**Comment by ScanMountGoat** [comment]
My initial goal with this project was just to automate some of the boilerplate code. It ended up being useful for people wanting to learn wgpu/webgpu as well since the generated code can prevent a number of subtle bugs.

> its usage of naga_oil now seems to prevent usage of pipeline-overridable constants

I wouldn't expect this to be a deal breaker for most projects. The override constants are modifying the final compiled program, so you can always modify the shader code itself before compilation. Any data that potentially changes should probably be a uniform anyway.

> if combined with no support for webgpu beyond debugging in some intermediate language...

wgpu on desktop or WebGPU in the browser will translate to Vulkan, DirectX 12, or Metal depending on the platform. WebGPU is conceptually very similar to any of the modern APIs. All that really changes in terms of debugging is the shader language and naming conventions like "descriptor sets" on Vulkan instead of "bind groups". I don't think the web debugging experience has ever been comparable to what's available on desktop. RenderDoc is great if you can manage to get it working. You can also try debuggers from the GPU vendor like Nsight graphics on Nvidia or a comparable tool from AMD or Intel. 

> I simply want as much debug information as possible, or at least the ability to set these values when I come upon an issue.

I don't think this is worth changing the public API of the generated code. I'll try and look into generating some basic non configurable labels based on the resource index or source name.

**Comment by 9SMTM6** [comment]
> I don't think this is worth changing the public API of the generated code. I'll try and look into generating some basic non configurable labels based on the resource index or source name.

That would be perfect.

> My initial goal with this project was just to automate some of the boilerplate code. It ended up being useful for people wanting to learn wgpu/webgpu as well since the generated code can prevent a number of subtle bugs.

Yeah. And because of that boilerplate removal and avoidance of subtle errors it can speed up iteration speed / make me actually willing to experiment a bit with the stuff I send between webgpu and Rust. That was the reason I looked for something like this.

> I wouldn't expect this to be a deal breaker for most projects. The override constants are modifying the final compiled program, so you can always modify the shader code itself before compilation.

You're probably right. But due to its simpler nature your project supports these `for free`  AFAIK (minus some developer experience that #58 was about). The same will, I expect, be true for other features, since you rely just on naga (with just wgsl-in), anything that works to be passed to wgsl will likely work here.

> wgpu on desktop or WebGPU in the browser will translate to Vulkan, DirectX 12, or Metal depending on the platform. WebGPU is conceptually very similar to any of the modern APIs.

Yeah I am theoretically aware of this, but with me not being knowledgeable I wasn't sure how close these would be. And I've yet to get a really problematic issue, but in that case I wanted to not be blocked from debugging by some of my dependencies, that's why I made this issue.

AFAIK WebGPU was originally intended to closely match Vulkan, but moved away from that. So between doing debugging with Nsight on Windows (where it should be translated to Dx12) and getting renderdoc to work on Linux, would you have a recommendation? (sorry for sidetracking).

And thank you!

**Comment by ScanMountGoat** [comment]
This is implemented for bind groups and bind group layouts, so I'm marking this as resolved.
